services:
  serve:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/book

  build-site:
    build: .
    command: properdocs build
    volumes:
      - .:/book

  build-pdf:
    build: .
    command: properdocs build
    environment:
      - MKDOCS_PDF=true
    volumes:
      - .:/book

  build-epub:
    build: .
    command: properdocs build
    environment:
      - MKDOCS_EPUB=true
    volumes:
      - .:/book
